name: Post-Deployment Check

on:
  push:
    branches:
      - main

jobs:
  post-deploy:
    name: Run Post-Deployment Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Wait for deployment
        run: |
          echo "Waiting for deployment to stabilize..."
          sleep 300  # Wait 5 minutes

      - name: Run deployment tests
        id: deployment-test
        run: |
          npm test -- test/deployment.test.ts || echo "::set-output name=status::failed"

      - name: Run post-deployment check
        if: always()
        run: npm run post-deploy
        env:
          NODE_ENV: production
          WORKFLOW_NAME: ${{ github.workflow }}
          WORKFLOW_STATUS: ${{ steps.deployment-test.outcome }}
          WORKFLOW_RUN_ID: ${{ github.run_id }}
          WORKFLOW_TRIGGER: ${{ github.event_name }}
          DEPLOYMENT_URL: ${{ secrets.DEPLOYMENT_URL }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          # Discord Configuration
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          APP_ID: ${{ secrets.DISCORD_APP_ID }}
          DISCORD_PUBLIC_KEY: ${{ secrets.DISCORD_PUBLIC_KEY }}
          DISCORD_SERVER_ID: ${{ secrets.DISCORD_SERVER_ID }}
          # Channel IDs
          DISCORD_GITHUB_CHANNEL_ID: ${{ secrets.DISCORD_GITHUB_CHANNEL_ID }}
          # Optional: Configure this if you want to enable feedback functionality
          FEEDBACK_CHANNEL_ID: ${{ secrets.FEEDBACK_CHANNEL_ID }}
