name: Test Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci
        
      - name: Run Tests
        id: test-run
        run: |
          npm test -- --reporters=default --reporters=jest-junit
        continue-on-error: true

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: junit.xml

      - name: Notify Server on Failure
        if: failure()
        run: |
          curl -X POST \
          -H "Content-Type: application/json" \
          -H "X-Signature: ${{ secrets.API_SIGNATURE }}" \
          -d '{
            "status": "failed",
            "run_id": "${{ github.run_id }}",
            "repo": "${{ github.repository }}",
            "commit": "${{ github.sha }}",
            "actor": "${{ github.actor }}",
            "details_url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
            "test_results": "${{ steps.test-run.outcome }}"
          }' \
          "${{ secrets.NOTIFICATION_WEBHOOK_URL }}"